#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH -t 24:00:00
#SBATCH --mem=150000
#SBATCH --account=CSBLRivanna
#SBATCH --partition=standard

module load gcc/9.2.0
module load bowtie2/2.2.9
module load samtools/1.10

# Quality trim the samples
/home/med4jn/sickle/sickle pe -t sanger -q 25 -f ${1}_1.fastq -r ${1}_2.fastq \
        -o ${1}_1.trim.fastq \
        -p ${1}_2.trim.fastq \
        -s ${1}.orphan.trim.fastq

# Paired reads
bowtie2 -q --fr -x Klebsiella_genes \
        -1 ${1}_1.trim.fastq \
        -2 ${1}_2.trim.fastq \
        -S ${1}_paired_reads.sam
samtools view -bS ${1}_paired_reads.sam > ${1}_paired_reads.bam
samtools sort ${1}_paired_reads.bam -o ${1}_paired_reads.sorted.bam
rm ${1}_paired_reads.bam ${1}_paired_reads.sam

# Orphaned reads
bowtie2 -q -x Klebsiella_genes \
        -U ${1}.orphan.trim.fastq \
        -S ${1}_orphan_reads.sam
samtools view -bS ${1}_orphan_reads.sam > ${1}_orphan_reads.bam
samtools sort ${1}_orphan_reads.bam -o ${1}_orphan_reads.sorted.bam
rm ${1}_orphan_reads.bam ${1}_orphan_reads.sam

# Merge alignments then remove duplicates
samtools merge ${1}_reads.merge.bam ${1}_paired_reads.sorted.bam ${1}_orphan_reads.sorted.bam
samtools sort ${1}_reads.merge.bam -o ${1}_reads.merge.sort.bam
rm ${1}_reads.merge.bam ${1}_paired_reads.sorted.bam ${1}_orphan_reads.sorted.bam

# Convert to human-readable format
samtools idxstats ${1}_reads.merge.sort.bam > ${1}.mapped.tsv
# rm ${1}_reads.merge.sort.bam
